apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: payment-network-latency
  namespace: default
spec:
  appinfo:
    appns: default
    applabel: app=payment-service
    appkind: deployment
  chaosServiceAccount: litmus-admin
  experiments:
    - name: pod-network-latency
      spec:
        components:
          env:
            - name: NETWORK_LATENCY
              value: "2000"
            - name: TOTAL_CHAOS_DURATION
              value: "60"
            - name: TARGET_CONTAINER
              value: "payment-service"
